name:  Basic Workflow 

on:  
  push :
    branches: 
      - main 
  workflow_dispatch:
  

jobs: 
  run_apitest:
    runs-on: ubuntu-latest
    steps:
      - name: run the apitest
        uses: action/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
      - name : required installs
        run: |
          python -m pip install --upgrade pip
          pip install -r ./apitesting/requirements.txt
      - name: run the tests
        run: |
          pytest
          
      - name : upload test report
        uses: actions/upload-artifact@v4
        with:
          name: apitest-report
          path : ./apitesting/report*.html